### ISSUE TITLE
Reload not working, if there is a space in the path

### ISSUE THREAD

**Issue by JoachimM7** [dperrymorrow/electron-css-reload#3]
`fs.watchFile` doesn't work, if there is a space in the path name, because then instead of the space, there will be a `%20`. Replacing it will work, so:

    try {
      deps.forEach((dep) => {
        dep = dep.replace(/%20/g, " ")
        console.log(`watching ${dep} for changes`);
        ...

**Comment by dperrymorrow** [comment]
well i wouldnt think you would have a space in a pathname that you are intending for the web. But nice fix. Pull requests welcome!

**Comment by dperrymorrow** [comment]
closed by #5
